version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  flask_app:
    build: .
    container_name: flask_app
    restart: always
    depends_on:
      - mongo
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/lyrics_db
